[package]
name = "qoi-rs"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["lib", "staticlib", "cdylib"]

[target.'cfg(target_family = "wasm")'.dependencies]
wee_alloc = "*"

[dev-dependencies]
image = "0.25.9"

[workspace]
members = ["qoi-viewer"]
